version: '2'
services:
  spec:
    build: .
    environment:
      - BUNDLE_PATH=/bundle
    working_dir: /check-monocle
    volumes:
      - .:/check-monocle
    volumes_from:
      - bundle
    dns: 8.8.8.8
  bundle:
    image: busybox
    volumes:
      - /bundle
